feat(products):  added POST /products route
csps/api pull request #30
Opened 2023-07-04 15:44 UTC by ampats04

2023-07-05 07:15 UTC, mavyfaby commented
With the introduction of Product variations, we need to also add a bridge table for `products` and `variations`.

2023-07-05 07:16 UTC, mavyfaby requested changes

2023-07-05 07:16 UTC, mavyfaby commented on src/db/models/product.ts
> +    if (data.thumbnail.trim().length === 0) return ["Thumbnail is required!", "thumbnail"];
Set thumbnail data type to int (Photo ID)

2023-07-05 07:16 UTC, mavyfaby commented on src/db/models/product.ts
> +    if (data.stock.length < 0) return ["Stocks must not be below 0", "stock"];
Add variations also which is a custom type:

```ts
type ProductVariation {
    type: string; // Variation type e.g. ("color", "sizes")
    name: string; // Variation name e.g. ("Red", "Large")
    photoID: number; // Product variation photo ID
}
```

2023-07-05 14:31 UTC, mavyfaby commented
Re-opened issue #4 and #5 due to changes.

2023-07-10 06:30 UTC, mavyfaby commented
Updates?

2023-07-10 07:49 UTC, ampats04 commented
I'll push the one I've made last week, still wasn't able to continue due to
High Fever and Extreme Dehydration

> Message ID: ***@***.***>
>

2023-07-14 12:52 UTC, mavyfaby approved these changes

2023-07-14 12:52 UTC, merged